spring.datasource:
  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:log4jdbc:mysql://localhost:3306/oneourbe?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
  username: me
  password: th5481th
  connection-test-query: SELECT 1
  maxWait: 3000 #풀에 커넥션이 존재하지 않을때, 커넥션이 풀에 다시 리턴되기까지 대기시간 1/1000초단위 -1일경우 무한대기
  minIdle: 5 #사용되지 않고 풀에 저장될수 있는 최소 커넥션수
  maxActive: 20 #커넥션풀이 제공할 최대 커넥션수
  initialSize: 5 #초기에 생성될 커넥션수
spring.profiles:
  active: dev

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

info:
  app:
    name: oneourbe
    domain: http://localhost:8080
spring:
  application:
    name: oneourbe

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      static-path-pattern: /resources/**

  servlet:
    encoding:
      enabled: true

